### ISSUE TITLE
Release into Jade

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit_metapackages#6]
Raised https://github.com/ros-planning/moveit_ros/issues/692

If write access to this repo and release-repo is given, I can work on it.

**Comment by v4hn** [comment]
is there a particular reason why you're not part of the moveit dev team?
Given that you are taking care of releases in many of the repos that might make sense..

**Comment by davetcoleman** [comment]
I just added you to the "MoveIt! Developers" team - you were previously on a  team called "MoveIt! Robots"(?) with fewer repos

**Comment by 130s** [comment]
Okay thanks for the access rights.

I tried blooming and got stuck at:
- https://github.com/ros-planning/moveit_setup_assistant/issues/106
- Also noticed that `moveit_pr2` is included in the release of `moveit_full`. But it's not there either http://repositories.ros.org/status_page/ros_jade_default.html?q=moveit_pr2

For PR2, I don't know the release status of it. Are necessary PR2 components already released or not. 

If they are not, do we still want to include `moveit_pr2` in the release of `moveit_full`? I'm not sure if trying to encourage PR2 maintainers for the new release in Jade is what MoveIt! maintainers do.

**Comment by v4hn** [comment]
On Fri, Jun 24, 2016 at 06:33:33AM -0700, Isaac I.Y. Saito wrote:
> For PR2, I don't know the release status of it. Are necessary PR2 components already released or not. 

All modules required by moveit_pr2 are released into jade.
The future of the pr2 stacks is not clear at the moment,
so releases into kinetic and future distros (though likely) are currently unclear.

> If they are not, do we still want to include `moveit_pr2` in the release of `moveit_full`?

It should be perfectly possible to include moveit_pr2 in jade afaics.

**Comment by mikeferguson** [comment]
Now part of consolidated repo, will be released in step with that
