### ISSUE TITLE
Metapackage for deploying MoveIt! on robots

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit_metapackages#9]
Out of low importance.

`moveit` metapackage includes `moveit_setup_assistant`. While having it installed with a single command is convenient for developers, installing it on the robots might not be necessary.
To even improve deployment process onto robots, having a package suite that depends only on runtime packages might be convenient. `moveit_full` with the current list of packages seems to serve for this purpose but its name doesn't. Something like moveit_runtime?

**Comment by v4hn** [comment]
+1 This would be great to have!
Users asked for such a package a number of times already...

**Comment by 130s** [comment]
Closed via #10.
